apiVersion: v2
name: aegis
description: Aegis GPU/AI infrastructure incident control plane
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: kafka
    version: 31.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: etcd
    version: 10.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: etcd.enabled
  - name: mailpit
    version: 0.34.1
    repository: https://jouve.github.io/charts/
    condition: mailpit.enabled
