apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aegis-agent
  namespace: aegis
spec:
  selector:
    matchLabels:
      app: aegis-agent
  template:
    metadata:
      labels:
        app: aegis-agent
    spec:
      containers:
        - name: agent
          image: aegis-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: AEGIS_CP_BOOTSTRAP_URLS
              value: "aegis-control-plane:50051"
            - name: AEGIS_WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AEGIS_SIMULATION_MODE
              value: "normal"
            - name: AEGIS_TELEMETRY_DATA_SOURCE
              value: "MOCK"
            - name: AEGIS_AGENT_API_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
