apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: aegis-system
  labels:
    app: mailpit
    infra: "true"
spec:
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
        infra: "true"
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:v1.30.3
          ports:
            - containerPort: 1025
            - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: aegis-system
  labels:
    app: mailpit
    infra: "true"
spec:
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
  selector:
    app: mailpit
