apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: aegis
name: aegis
chartHome: ../../../helm
releaseName: aegis
namespace: aegis-system
valuesFile: ../local/values-local.yaml
valuesInline:
  kafka:
    externalAccess:
      controller:
        service:
          nodePorts: [30098, 30099, 30100]
includeCRDs: true
