apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-control-plane
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-agent
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-composer
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-sink-worker
  namespace: {{ .Values.global.namespace }}

